apiVersion: v1
kind: Service
metadata:
  name: productcatalogue
  labels:
    app: productcatalogue
spec:
  ports:
  - protocol: TCP
    port: 8020
  selector:
    app: productcatalogue
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: productcatalogue
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: productcatalogue
    spec:
      containers:
        - image: 10.128.0.6:8081/microsvc-dev/djproductcatalogue:12
          imagePullPolicy: Always
          name: productcatalogue
          ports:
            - containerPort: 8020
